abbr --add j "jj"
abbr --add ja "jj abandon"
abbr --add jab "jj absorb"
abbr --add jc "jj commit"
abbr --add jd "jj diff"
abbr --add jde "jj describe"
abbr --add jdu "jj duplicate"
abbr --add je "jj edit"
abbr --add jl "jj log"
abbr --add jn "jj new"
abbr --add jx "jj next"
abbr --add jp "jj prev"
abbr --add jrb "jj rebase"
abbr --add jrs "jj restore"
abbr --add jrv "jj resolve"
abbr --add jw "jj show"
abbr --add jsp "jj split"
abbr --add jsq "jj squash"
abbr --add js "jj status"
abbr --add jun "jj undo"
abbr --add jrd "jj redo"
abbr --add jel "jj evolog"
abbr --add jgc "jj git clone"
abbr --add jgf "jj git fetch"
abbr --add jgi "jj git init"
abbr --add jgp "jj git push"
abbr --add jbc "jj bookmark create"
abbr --add jbd "jj bookmark delete"
abbr --add jbf "jj bookmark forget"
abbr --add jbl "jj bookmark list"
abbr --add jbm "jj bookmark move"
abbr --add jbr "jj bookmark rename"
abbr --add jbs "jj bookmark set"
abbr --add jbt "jj bookmark track"
abbr --add jbu "jj bookmark untrack"
abbr --add jol "jj op log"
abbr --add jor "jj op restore"
abbr --add jds "jj diff --summary"
abbr --add jls "jj log --summary"
abbr --add jws "jj show --summary"
abbr --add jdst "jj diff --stat"
abbr --add jlst "jj log --stat"
abbr --add jwst "jj show --stat"
abbr --add jlp "jj log --patch"
abbr --add jdg "jj diff --git"
abbr --add jlg "jj log --git"
abbr --add jwg "jj show --git"
abbr --add jgfa "jj git fetch --all-remotes"
abbr --add jbla "jj bookmark list --all-remotes"
abbr --add jgpa "jj git push --all"
abbr --add jci "jj commit --interactive"
abbr --add jsqi "jj squash --interactive"
abbr --add jdr "jj diff -r"
abbr --add jlr "jj log -r"
abbr --add jsqr "jj squash -r"
abbr --add jgpr "jj git push -r"
abbr --add jblr "jj bookmark list -r"
abbr --add jbsr "jj bookmark set -r"
abbr --add jdsr "jj diff --summary -r"
abbr --add jlsr "jj log --summary -r"
abbr --add jdstr "jj diff --stat -r"
abbr --add jlstr "jj log --stat -r"
abbr --add jlpr "jj log --patch -r"
abbr --add jdgr "jj diff --git -r"
abbr --add jlgr "jj log --git -r"
abbr --add jblar "jj bookmark list --all-remotes -r"
abbr --add jsqir "jj squash --interactive -r"
abbr --add jcm "jj commit -m"
abbr --add jdem "jj describe -m"
abbr --add jnm "jj new -m"
abbr --add jsqm "jj squash -m"
abbr --add jcim "jj commit --interactive -m"
abbr --add jsqim "jj squash --interactive -m"
abbr --add jgpc "jj git push -c"
abbr --add jrbo "jj rebase -o"
abbr --add jnma "jj new main"
abbr --add jrboma "jj rebase -o main"
abbr --add jgfn "jj git fetch && jj new"
abbr --add jgfnma "jj git fetch && jj new main"
abbr --add jgfrbo "jj git fetch && jj rebase -o"
abbr --add jgfrboma "jj git fetch && jj rebase -o main"
